title: "Puppy Kidney Disease"
author: "Edwin Fung"
description: "<b>Disclaimer:</b> I am not a veterinarian, nutritionist, or animal behavior specialist. I created this website to share my own experiences and learnings as a first-time dog-owner, supporting a puppy with kidney disease. I do not charge any money for any information on this website. Opinions expressed on this website are that of my own and should not be taken as medical advice. This website is not intended to be used to diagnose or treat any dog.   Please consult your veterinarian for their professional opinion on how to best support your dog."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "blog.html", title: "Posts"}
  - {file: "_posts/2022-08-07-journey1.md", title: "Arlo's Journey"}
  - {file: "journey.md", title: "Useful Links"}
  - {file: "index.html", title: "About"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:edwin@puppykidneydisease.com"}
#  - {title: Github, icon: github, url: "https://github.com/fungedwin"}
#  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
